### ISSUE TITLE
Add HYPE to open problem 5

### ISSUE THREAD

**Issue by leonoverweel** [distillpub/post--gan-open-problems#1]
Open problem 5 (How Should we Evaluate GANs and When Should we Use Them?) lists a number of proposed metrics for evaluating GANs. Zhou et al. recently (on April 1, 2019) proposed a new metric: _HYPE: Human eYe Perceptual Evaluation of Generative Models_ ([paper on arXiv](https://arxiv.org/abs/1904.01121); [hype.stanford.edu](https://hype.stanford.edu/)), which is not yet in this list. Perhaps it'd be good to add it there?

I'm not sure what the process is for this, so instead of adding it myself and making a pull request, I figured it'd be easier to discuss it as an issue here first.

**Comment by leonoverweel** [comment]
@DoctorTeeth hey, any thoughts on this?

**Comment by DoctorTeeth** [comment]
Hey, feel free to make a PR if you think there’s a nice way to work it in.
I didn’t see it when we wrote the original post as most of the work for
that was done in late 2018 early 2019

**Comment by leonoverweel** [comment]
@DoctorTeeth, thanks, I've made PR here: #2.

**Comment by DoctorTeeth** [comment]
should be merged, thanks!

**Comment by leonoverweel** [comment]
Thanks! Do you know when it'll be rebuilt and show up on the [distill.pub](https://distill.pub) version of the article?
